# Base build image
FROM golang:1.17-alpine3.13 AS build

# Install Git
RUN apk update && apk add git

# Set workdir
WORKDIR /go/src/go/src/gitlab.com/

# Force the go compiler to use modules
# ENV GO111MODULE=on

# Copy project content
RUN echo "Copying resources..."
COPY . .
RUN echo "Copied."

# Compile the project
ENV CGO_ENABLED=0 GOOS=linux
RUN echo "Compiling..."
RUN go build -mod=vendor -o /go/bin/urlcollector cmd/urlcollector.go
RUN echo "Compile output in: /go/bin/urlcollector"

# Coying only the results without the artifacts to fresh Alpine image.
FROM alpine
WORKDIR /srv
COPY --from=build /go/bin/urlcollector ./urlcollector

# Entrypoint
ENTRYPOINT ./urlcollector -json-api-port 8080 -nasa-api-key-envar API_KEY -logging-level all
